### ISSUE TITLE
Correcciones

### ISSUE THREAD

**Issue by migueldelamo** [greyzeids/todo-list-application#1]
En el resto de lugares que seteas el state, lo haces bien, pero aquí no. Debes usar la forma: 
`setState(prevState => {...}`
https://github.com/greyzeids/todo-list-application/blob/6e371d70e90ed771d87e39979dba8e25f934840e/src/js/component/TodoList.jsx#L29

**Comment by greyzeids** [comment]
Hola Miguel, he refactorizado tres funciones del todolist para que usen el estado previo y no el actual, creo que ahora esta bien cualquier cosa me dices gracias
